### ISSUE TITLE
Pull request #2532

### ISSUE THREAD

**Issue by monooz23** [ordinals-wallet/ordinals-collections#2536]
Hi Guys, need some help with this pull request....not sure why its failing the checks?

**Comment by MMCCSolana** [comment]
Not on the team... but helpful hint @monooz23 . ChatGPT is great at troubleshooting stuff like this. 

In your case:

The error messages suggest that there are three tests failing:

test_meta: This test is failing because it expects all values of keys ending in 'link' to start with 'https://' or 'http://'. It seems that one or more of your 'link' values in your meta.json files starts with '@Monooz23' instead, hence the test failure.

test_inscriptions: This test is failing because it's not able to load your inscriptions.json file as a valid JSON. The error message suggests that there's an issue at line 338 column 1 of the JSON file. There may be a missing or incorrect character there.

test_uniqueness: This test is also failing to load your inscriptions.json file, for the same reasons as test_inscriptions.

You will need to examine the JSON files that are causing the errors. For the first error, check the meta.json files for incorrect link values that don't start with 'http://' or 'https://'. For the second and third errors, check the inscriptions.json file at the specified line and column for any discrepancies that could make it an invalid JSON.

Using a JSON validator could help identify the issues in your JSON files. Once these issues are corrected, the tests should pass.

**Comment by monooz23** [comment]
> 

Thank you so much for your help.
For the twitter handle do I add the link using the http path to my twitter profile?

**Comment by monooz23** [comment]
> > 
> 
> Thank you so much for your help. I have updated the link value. I cant seem to find this problem at 338?...this is the last line of the code?

Great, Thanks again.
The JSON Validator was a great suggestion.
Much appreciated
