### ISSUE TITLE
Add new collection 500 squares #2868

### ISSUE THREAD

**Issue by monooz23** [ordinals-wallet/ordinals-collections#2869]
can I get some help with merging my project please.

I really appreciate everything you guys are doing and I know you must really busy.

Please help, I'm new to github and am really struggling to work this out on my own.

@MillHaus33 
@cliobitcoinbank

**Comment by cliobitcoinbank** [comment]
I commented on your other thread, do not make multiple threads.  Can I confirm that you have your folder renamed to your slug and it doesnt have spaces or other characters??  Dont even reply here, close this and reply on the other Issue

**Comment by cliobitcoinbank** [comment]
No no no no no you did not make a pull request and open an issue 10 minutes later did you?  Did you?

**Comment by monooz23** [comment]
Sorry bro,
Have been trying to get help on this for days and I have no-one I know who uses github so I'm really reliant on you guys and myself to work out these problems.
Sorry if I stuffed something up.
I closed the other thread as I have stopped trying to clone to my local and instead have uploaded the files through the repo on the browser. This seemed to have worked but the checks failed?...I don't believe there is anything wrong with the code and have used a validator to verify which returns a positive result.

Appreciate your help and any advice will be appreciated.

Thanks

**Comment by cliobitcoinbank** [comment]
The previous problem was possibly related to the folder names, not sure tho.  I'll take a look at the files but it'll be 24 hours before somebody who can merge your pull request will get to it.  Come check back and if most of the pull requests in front of yours are gone, then we can open an issue on it and get to the bottom of it.  Until then, try to look at some of the examples in the instructions on the main page, each file is layed out a little differently so make sure you are in compliance.  I could be wrong, but some errors might not be totally disqualifying so let the maintainers check it first just in case you're correct about your code being right and you're already on your way to being listed.  If you want to go get more listing done while you are waiting, lookup the Ordswap twitter, follow their discord link, and you can apply to have your collection listed on Ordswap, a market site who do not use this repository and instead ask you to follow a listing process in their discord channel.

**Comment by cliobitcoinbank** [comment]
Try removing the comment codes maybe?

**Comment by monooz23** [comment]
thanks for getting back to me, really appreciate it
I'll check back tomorrow

already removed comment codes

**Comment by cliobitcoinbank** [comment]
https://github.com/ordinals-wallet/ordinals-collections/pull/2876/files

**Comment by monooz23** [comment]
@cliobitcoinbank 

Hi bro, what is the link for?...  2876 isn't my project?

**Comment by monooz23** [comment]
@cliobitcoinbank 

this is my collection:    
https://github.com/ordinals-wallet/ordinals-collections/pull/2868

**Comment by monooz23** [comment]
@cliobitcoinbank @MillHaus33 

Please can you help me......not sure why my pull request isn't getting merged?

**Comment by cliobitcoinbank** [comment]
Looks like you got 2 pages of pull requests in front of you.  Apologies for the long wait, unfortunately the manual human review process is the only thing that prevents theft, lawsuits over IP, and "bad stuff" from making it into major collections.  That is what makes this github repository so popular, you know if you use it for your tool or website you won't go to jail or be sued.

Ordinals started alpha in January.  "We are early.TM"  Parent-Child Ordinals are a way of Organizing collections into child parent grandparent relationships that is a planned update of the Ord protocol that will decentralize the collection process.  In time, you may grow to appreciate standing in this line because of the early mover advantage that creating ordinals this early will grant you and your collection. Thats why I'm spending time meeting the other OG's like you, and reviewing their questions while I wait and trying to help solve them or smooth the process for maintainers.  Personally and professionally, I have been waiting almost 2 months for them to update my collection and add some new ordinals to it.  https://github.com/ordinals-wallet/ordinals-collections/issues/2323  I guess my point is, we feel your pain but your collection will do better and make more money if, instead of posting about the wait times, you help others that might be stuck with an issue you can fix.  I hope this helps, you can go into ordswaps discord and start the process to get your collection listed on ordswap, they use a separate process of applying to be a collection in their discord tech support section.  Good luck.

**Comment by monooz23** [comment]
Thanks for for your response, I appreciate all the assistance.
I will continue to be patient wit this process which is new to me as I have never really used github before.
We are all learning I guess.
Sorry to hear you have been waiting so long.
I guess my initial experience with this repository seemed very efficient a few months ago, I guess there are alot more pople adding collections now.
I have seen alot of pull request being merged after mine.
I initially submitted mine over a  month ago but as I'm new removed it because I thought there was something wrong.
I will always help others if I can but currently my skills are quiet limited.
Thanks again for your time and support

**Comment by monooz23** [comment]
Hi I have added a new Pull Rquest for my collaection as the previous one was closed ( https://github.com/ordinals-wallet/ordinals-collections/commit/29fd5d6ea3d6354769cddc86821c1506ac0d97f9 ) without any info why.?
@MillHaus33 

Just trying to understand what the issue is so I can fix this, Any advice appreciated.
New Pull request #2953

**Comment by monooz23** [comment]
@MillHaus33 
disappointed I can't get my collection merged, really poor assistance.
bad experience and poor communication
thanks for your help or lack of it
